# Generated by Django 5.0.4 on 2024-04-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactlist', '0003_remove_contatos_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='celular',
            field=models.CharField(blank=True, default=None, help_text='Fone de contato com DDD (63) 98765-4321', max_length=11, null=True, unique=True, verbose_name='Celular com DDD'),
        ),
    ]
