# Generated by Django 5.0.4 on 2024-04-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatos',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem que será mostrada em seu Perfil', null=True, upload_to='contato', verbose_name='Imagem do Contato'),
        ),
    ]
