# Generated by Django 5.0.4 on 2024-04-25 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactlist', '0002_contatos_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contatos',
            name='ativo',
        ),
    ]
